DROP TABLE IF EXISTS citation_map;
DROP TABLE IF EXISTS opinions;
DROP TABLE IF EXISTS opinion_clusters;
DROP TABLE IF EXISTS dockets;
DROP TABLE IF EXISTS courts;

CREATE TABLE courts (
    id VARCHAR(15) PRIMARY KEY,
    pacer_court_id VARCHAR(50),
    pacer_has_rss_feed BOOLEAN,
    pacer_rss_entry_types TEXT,
    date_last_pacer_contact TIMESTAMP,
    fjc_court_id VARCHAR(50),
    date_modified TIMESTAMP,
    in_use BOOLEAN,
    has_opinion_scraper BOOLEAN,
    has_oral_argument_scraper BOOLEAN,
    position NUMERIC,
    citation_string VARCHAR(100),
    short_name VARCHAR(100),
    full_name VARCHAR(200),
    url VARCHAR(500),
    start_date DATE,
    end_date DATE,
    jurisdiction VARCHAR(10),
    notes TEXT,
    parent_court_id VARCHAR(15)
);

CREATE TABLE dockets (
    id BIGINT PRIMARY KEY,
    date_created TIMESTAMP,
    date_modified TIMESTAMP,
    source SMALLINT,
    appeal_from_str TEXT,
    assigned_to_str TEXT,
    referred_to_str TEXT,
    panel_str TEXT,
    date_last_index TIMESTAMP,
    date_cert_granted DATE,
    date_cert_denied DATE,
    date_argued DATE,
    date_reargued DATE,
    date_reargument_denied DATE,
    date_filed DATE,
    date_terminated DATE,
    date_last_filing DATE,
    case_name_short TEXT,
    case_name TEXT,
    case_name_full TEXT,
    slug VARCHAR(75),
    docket_number TEXT,
    docket_number_core TEXT,
    pacer_case_id VARCHAR(100),
    cause TEXT,
    nature_of_suit TEXT,
    jury_demand TEXT,
    jurisdiction_type TEXT,
    appellate_fee_status TEXT,
    appellate_case_type_information TEXT,
    mdl_status TEXT,
    filepath_local TEXT,
    filepath_ia TEXT,
    filepath_ia_json TEXT,
    ia_upload_failure_count INTEGER,
    ia_needs_upload BOOLEAN,
    ia_date_first_change TIMESTAMP,
    view_count INTEGER,
    date_blocked DATE,
    blocked BOOLEAN,
    appeal_from_id VARCHAR(15),
    assigned_to_id BIGINT,
    court_id VARCHAR(15),
    idb_data_id BIGINT,
    originating_court_information_id BIGINT,
    referred_to_id BIGINT,
    federal_dn_case_type VARCHAR(50),
    federal_dn_office_code VARCHAR(50),
    federal_dn_judge_initials_assigned VARCHAR(50),
    federal_dn_judge_initials_referred VARCHAR(50),
    federal_defendant_number INTEGER,
    parent_docket_id BIGINT
);

CREATE TABLE opinion_clusters (
    id BIGINT PRIMARY KEY,
    date_created TIMESTAMP,
    date_modified TIMESTAMP,
    judges TEXT,
    date_filed DATE,
    date_filed_is_approximate BOOLEAN,
    slug VARCHAR(75),
    case_name_short TEXT,
    case_name TEXT,
    case_name_full TEXT,
    scdb_id VARCHAR(10),
    scdb_decision_direction SMALLINT,
    scdb_votes_majority INTEGER,
    scdb_votes_minority INTEGER,
    source VARCHAR(10),
    procedural_history TEXT,
    attorneys TEXT,
    nature_of_suit TEXT,
    posture TEXT,
    syllabus TEXT,
    headnotes TEXT,
    summary TEXT,
    disposition TEXT,
    history TEXT,
    other_dates TEXT,
    cross_reference TEXT,
    correction TEXT,
    citation_count INTEGER,
    precedential_status VARCHAR(50),
    date_blocked DATE,
    blocked BOOLEAN,
    filepath_json_harvard TEXT,
    filepath_pdf_harvard TEXT,
    docket_id BIGINT,
    arguments TEXT,
    headmatter TEXT
);

CREATE TABLE opinions (
    id BIGINT PRIMARY KEY,
    date_created TIMESTAMP,
    date_modified TIMESTAMP,
    author_str TEXT,
    per_curiam BOOLEAN,
    joined_by_str TEXT,
    type VARCHAR(20),
    sha1 VARCHAR(40),
    page_count INTEGER,
    download_url VARCHAR(500),
    local_path TEXT,
    plain_text TEXT,
    html TEXT,
    html_lawbox TEXT,
    html_columbia TEXT,
    html_anon_2020 TEXT,
    xml_harvard TEXT,
    html_with_citations TEXT,
    extracted_by_ocr BOOLEAN,
    author_id BIGINT,
    cluster_id BIGINT
);

CREATE TABLE citation_map (
    id BIGINT PRIMARY KEY,
    depth INTEGER,
    cited_opinion_id BIGINT,
    citing_opinion_id BIGINT
);
